"""Row-invariant small-M matmul for every weight format (see ``matmul``)."""

from .installer import (
    LAW_ID,
    LAW_IDS,
    ProjectionGroup,
    apply_policy,
    install,
    installed,
    law_id,
    set_enabled,
    stats,
    uninstall,
)
from .matmul import (
    GROUP_SIZES,
    MAX_ROWS,
    QUANT_BITS,
    UNQUANTIZED_BITS,
    LaneUnsupported,
    LaneWeights,
    available,
    backend,
    force_backend,
    lane_matmul,
    prepare,
    split_k,
)

__all__ = [
    "GROUP_SIZES",
    "LAW_ID",
    "LAW_IDS",
    "MAX_ROWS",
    "QUANT_BITS",
    "UNQUANTIZED_BITS",
    "LaneUnsupported",
    "LaneWeights",
    "ProjectionGroup",
    "apply_policy",
    "available",
    "backend",
    "force_backend",
    "install",
    "installed",
    "lane_matmul",
    "law_id",
    "prepare",
    "set_enabled",
    "split_k",
    "stats",
    "uninstall",
]
