"""Xing4.0 tokenizer: exact reference decode, streaming, stamp, and fast-build parity.

Model-free tests use the committed reference fixture
(``tests/fixtures/xing4_0_tokenizer/expected.json``, generated by
``scripts/xing4_0_tokenizer.py --write-fixture`` from the slow
``Xing4_0Tokenizer``).  Tests that build ``tokenizer.json`` need the 2.2 MB
``tokenizer.model``: set ``XING4_0_TOKENIZER_DIR`` to a directory holding it
(and ``chat_template.jinja``) or install the artifact under
``~/mlx-models/Xing4.0-*``; they skip cleanly otherwise.
"""

from __future__ import annotations

import importlib.util
import json
import os
import random
import shutil
from pathlib import Path

import pytest

from mlx2.adapters import xing_tokenizer as xt

ROOT = Path(__file__).resolve().parents[1]
FIXTURE = json.loads((ROOT / "tests/fixtures/xing4_0_tokenizer/expected.json").read_text())


def _converter():
    spec = importlib.util.spec_from_file_location("xing4_0_tokenizer_script", ROOT / "scripts/xing4_0_tokenizer.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _fixture_tables() -> xt._Tables:
    """The fixed Xing4.0 layout plus every real piece the fixture touches."""
    pieces = [f"▁filler{i}" for i in range(xt.VOCAB_SIZE)]
    for key, piece in FIXTURE["pieces"].items():
        pieces[int(key)] = piece
    return xt._Tables(pieces)


class _TablesOnly:
    def __init__(self, tables):
        self._xing_tables = tables


def _model_dir() -> Path | None:
    candidates = []
    if os.environ.get("XING4_0_TOKENIZER_DIR"):
        candidates.append(Path(os.environ["XING4_0_TOKENIZER_DIR"]))
    candidates += sorted(Path.home().glob("mlx-models/Xing4.0-*"))
    for candidate in candidates:
        model = candidate / "tokenizer.model"
        if model.exists() and xt.sha256_file(model) == FIXTURE["tokenizer_model_sha256"]:
            return candidate
    return None


MODEL_DIR = _model_dir()
needs_model = pytest.mark.skipif(MODEL_DIR is None, reason="Xing4.0 tokenizer.model not available")


# --------------------------------------------------------------------------
# Exact decode semantics (model-free)
# --------------------------------------------------------------------------


def test_fixture_decodes_match_reference_both_skip_modes():
    tables = _fixture_tables()
    assert len(FIXTURE["decode"]) >= 200
    for case in FIXTURE["decode"]:
        assert xt.decode_ids(tables, case["ids"]) == case["text"], case["ids"]
        assert xt.decode_ids(tables, case["ids"], True) == case["text_skip_special"], case["ids"]


def test_streaming_detokenizer_equals_full_decode_at_every_step():
    tables = _fixture_tables()
    for case in FIXTURE["decode"]:
        detok = xt.XingStreamingDetokenizer(_TablesOnly(tables))
        emitted = ""
        for index, token in enumerate(case["ids"]):
            detok.add_token(token)
            emitted += detok.last_segment
            # Everything emitted so far is final: a prefix of the full decode.
            assert case["text"].startswith(emitted)
            full_prefix = xt.decode_ids(tables, case["ids"][: index + 1])
            assert full_prefix.startswith(emitted)
        detok.finalize()
        emitted += detok.last_segment
        assert emitted == detok.text == case["text"]


def test_decode_rules_reproduce_sentencepiece_quirks():
    tables = _fixture_tables()
    w, ww = xt.SPIECE_ID, 396  # "▁", "▁▁"
    hi = 13029  # "▁hi"
    assert tables.pieces[hi] == "▁hi" and tables.pieces[ww] == "▁▁"
    byte = lambda b: xt.BYTE_OFFSET + b  # noqa: E731
    cases = {
        (4, hi): "<_user>hi",  # one leading ▁ stripped per run after a special
        (hi, hi): "hi hi",
        (w, hi): " hi",  # a lone ▁ is the consumed prefix; the next keeps its space
        (7, hi): "hi",  # unregistered control: "" and keeps the expectation
        (w, 7, hi): " hi",
        (0, hi): " ⁇  hi",  # <_unk>
        (byte(0xF0), byte(0x9F), hi): "�� hi",  # one U+FFFD per invalid byte
        (byte(0xF0), byte(0x9F), byte(0x98), byte(0x80)): "\U0001F600",
        (byte(0xF0), 7, byte(0x9F)): "��",  # a control piece splits byte runs
        (byte(0x20), hi): "  hi",
        (ww,): " ",
        (10, ww, 11): "</think> <tool_call>",
    }
    for ids, want in cases.items():
        assert xt.decode_ids(tables, list(ids)) == want, ids
    # skip_special_tokens removes specials first, so runs merge.
    assert xt.decode_ids(tables, [4, hi, 5, hi], True) == "hi hi"
    assert xt.decode_ids(tables, [4, hi, 5, hi]) == "<_user>hi<_bot>hi"
    with pytest.raises(IndexError):
        xt.decode_ids(tables, [xt.VOCAB_SIZE])


def test_streaming_random_sequences_match_full_decode():
    tables = _fixture_tables()
    rng = random.Random(3)
    pool = [int(k) for k in FIXTURE["pieces"]]
    for _ in range(2000):
        ids = [rng.choice(pool) for _ in range(rng.randint(0, 30))]
        detok = xt.XingStreamingDetokenizer(_TablesOnly(tables))
        for token in ids:
            detok.add_token(token)
        detok.finalize()
        assert detok.text == xt.decode_ids(tables, ids)


def test_streaming_rejects_a_padded_logits_id_with_a_value_error():
    """The logits row is wider than the vocabulary; a padded id is a caller
    error reported like the BPE detokenizer's, and leaves the stream intact."""
    detok = xt.XingStreamingDetokenizer(_TablesOnly(_fixture_tables()))
    hi = 13029  # "▁hi"
    detok.add_token(hi)
    for bad in (xt.VOCAB_SIZE, xt.VOCAB_SIZE + 7, -1):
        with pytest.raises(ValueError, match="unknown Xing4.0 token ID"):
            detok.add_token(bad)
    detok.finalize()
    assert detok.tokens == [hi]
    assert detok.text == xt.decode_ids(_fixture_tables(), [hi])


def test_tables_reject_a_foreign_vocabulary():
    pieces = [f"p{i}" for i in range(xt.VOCAB_SIZE)]
    with pytest.raises(xt.XingTokenizerError):
        xt._Tables(pieces)


# --------------------------------------------------------------------------
# Stamp and loader (model-free)
# --------------------------------------------------------------------------


def _fake_stamped_dir(tmp_path: Path) -> Path:
    for name in xt.STAMPED_FILES:
        (tmp_path / name).write_text(name)
    report = {"status": "pass", "counts": {"fuzz_strings": 20000}, "seed": 1}
    stamp = xt.make_stamp(tmp_path, report=report, versions={}, generated_at="now")
    (tmp_path / xt.STAMP_NAME).write_text(json.dumps(stamp))
    return tmp_path


def test_stamp_verification_fails_closed(tmp_path):
    with pytest.raises(xt.XingTokenizerError, match="no tokenizer parity stamp"):
        xt.verify_parity_stamp(tmp_path)
    artifact = _fake_stamped_dir(tmp_path)
    assert xt.verify_parity_stamp(artifact)["status"] == "pass"
    (artifact / "tokenizer.json").write_text("tampered")
    with pytest.raises(xt.XingTokenizerError, match="changed since"):
        xt.verify_parity_stamp(artifact)


def test_stamp_rejects_failed_or_undersized_runs(tmp_path):
    artifact = _fake_stamped_dir(tmp_path)
    stamp = json.loads((artifact / xt.STAMP_NAME).read_text())
    for patch in ({"status": "fail"}, {"counts": {"fuzz_strings": 10}}, {"schema": "other"}):
        (artifact / xt.STAMP_NAME).write_text(json.dumps({**stamp, **patch}))
        with pytest.raises(xt.XingTokenizerError):
            xt.verify_parity_stamp(artifact)


def test_loader_without_stamp_fails_closed_unless_fallback_enabled(tmp_path):
    with pytest.raises(xt.XingTokenizerError):
        xt.load_tokenizer(tmp_path)
    # Opt-in fallback still needs the reference code; it does not silently
    # degrade to anything else.
    with pytest.raises(xt.XingTokenizerError):
        xt.load_tokenizer(tmp_path, allow_reference_fallback=True)


def test_fast_tokenizer_config_drops_remote_code():
    reference = {"tokenizer_class": "Xing4_0Tokenizer", "auto_map": {"AutoTokenizer": ["x", None]},
                 "add_bos_token": False, "sp_model_kwargs": {}, "eos_token": "<_end>"}
    config = xt.fast_tokenizer_config(reference)
    assert config["tokenizer_class"] == "TokenizersBackend"
    assert "auto_map" not in config and "sp_model_kwargs" not in config
    assert config["eos_token"] == "<_end>" and config["add_bos_token"] is False


def test_normalize_messages_parses_openai_tool_arguments():
    messages = [
        {"role": "assistant", "content": "", "tool_calls": [
            {"id": "c1", "type": "function", "function": {"name": "f", "arguments": "{\"a\": 1}"}}]},
        {"role": "tool", "content": [{"output": "x"}]},
    ]
    out = xt.normalize_messages(messages)
    assert out[0]["tool_calls"][0]["function"]["arguments"] == {"a": 1}
    assert messages[0]["tool_calls"][0]["function"]["arguments"] == "{\"a\": 1}"
    with pytest.raises(TypeError):
        xt.normalize_messages([{"role": "assistant", "tool_calls": [{"function": {"name": "f", "arguments": "[1]"}}]}])
    with pytest.raises(ValueError):
        xt.normalize_messages([{"role": "user", "content": [{"type": "image_url", "image_url": {}}]}])


def test_converter_user_defined_pattern_is_leftmost_longest():
    import re

    conv = _converter()
    pattern = re.compile(conv.user_defined_pattern(["_", "__", "___", "____", "1", "\n", "<reserve1>", "<reserve10>"]))
    assert pattern.findall("a_____b<reserve10>\n1") == ["____", "_", "<reserve10>", "\n", "1"]


# --------------------------------------------------------------------------
# Fast build parity against the reference fixture (needs tokenizer.model)
# --------------------------------------------------------------------------


@pytest.fixture(scope="module")
def fast_dir(tmp_path_factory):
    if MODEL_DIR is None:
        pytest.skip("Xing4.0 tokenizer.model not available")
    conv = _converter()
    model = conv.read_spm_model(MODEL_DIR / "tokenizer.model")
    conv.validate_spm(model)
    out = tmp_path_factory.mktemp("xing_fast")
    conv.build_tokenizer(model).save(str(out / "tokenizer.json"))
    reference_config = MODEL_DIR / "tokenizer_config.reference.json"
    if not reference_config.exists():
        reference_config = MODEL_DIR / "tokenizer_config.json"
    config = json.loads(reference_config.read_text())
    (out / "tokenizer_config.json").write_text(json.dumps(xt.fast_tokenizer_config(config)))
    shutil.copy2(MODEL_DIR / "tokenizer.model", out / "tokenizer.model")
    if (MODEL_DIR / "chat_template.jinja").exists():
        shutil.copy2(MODEL_DIR / "chat_template.jinja", out / "chat_template.jinja")
    return out


@needs_model
def test_fast_encode_matches_reference_fixture(fast_dir):
    tokenizer = xt.load_fast_unverified(fast_dir)
    texts = [case["text"] for case in FIXTURE["encode"]]
    batch = tokenizer(texts, add_special_tokens=False)["input_ids"]
    for case, ids in zip(FIXTURE["encode"], batch):
        assert ids == case["ids"], case["text"]
        assert tokenizer.encode(case["text"]) == case["ids"]  # add_bos_token is false


@needs_model
def test_fast_decode_matches_reference_fixture(fast_dir):
    tokenizer = xt.load_fast_unverified(fast_dir)
    for case in FIXTURE["decode"]:
        assert tokenizer.decode(case["ids"]) == case["text"]
        assert tokenizer.decode(case["ids"], skip_special_tokens=True) == case["text_skip_special"]
    for key, piece in FIXTURE["pieces"].items():
        assert tokenizer.convert_ids_to_tokens(int(key)) == piece


@needs_model
def test_render_prompt_matches_reference_chat_template(fast_dir):
    if not (fast_dir / "chat_template.jinja").exists():
        pytest.skip("chat_template.jinja not available")
    tokenizer = xt.load_fast_unverified(fast_dir)
    wrapper = xt.make_tokenizer_wrapper(tokenizer)
    for case in FIXTURE["chat"]:
        tools = case["tools"] or None
        text = tokenizer.apply_chat_template(case["messages"], tools=tools, tokenize=False,
                                             add_generation_prompt=True, enable_thinking=case["enable_thinking"])
        assert text == case["text"]
        assert xt.render_prompt(tokenizer, case["messages"], tools, case["enable_thinking"]) == case["ids"]
        assert xt.render_prompt(wrapper, case["messages"], tools, case["enable_thinking"]) == case["ids"]
    on = xt.render_prompt(tokenizer, [{"role": "user", "content": "Hi"}], None, True)
    off = xt.render_prompt(tokenizer, [{"role": "user", "content": "Hi"}], None, False)
    assert on[-3:] == [xt.THINK_START_ID, xt.SPIECE_ID, 35]  # <think> ▁ \n
    assert off[-1] == xt.THINK_END_ID


@needs_model
def test_stamped_load_and_wrapper_route(fast_dir):
    report = {"status": "pass", "counts": {"fuzz_strings": 20000}, "seed": 0}
    if not (fast_dir / "chat_template.jinja").exists():
        pytest.skip("chat_template.jinja not available")
    stamp = xt.make_stamp(fast_dir, report=report, versions={}, generated_at="test")
    (fast_dir / xt.STAMP_NAME).write_text(json.dumps(stamp))
    tokenizer, receipt = xt.load_tokenizer(fast_dir)
    assert receipt["route"] == "fast-tokenizer-json" and receipt["trust_remote_code"] is False
    wrapper = xt.make_tokenizer_wrapper(tokenizer)
    assert wrapper.think_start_id == 9 and wrapper.think_end_id == 10
    assert wrapper.eos_token_ids == {2}
    text = "Reasoning 步骤 1 😀\n</think>Answer: 42<tool_call>f<param_key>x</param_key><param_value>1</param_value></tool_call>"
    ids = tokenizer.encode(text, add_special_tokens=False)
    detok = wrapper.detokenizer
    for token in ids:
        detok.add_token(token)
    detok.finalize()
    assert detok.text == tokenizer.decode(ids) == text
    (fast_dir / "tokenizer.json").write_text((fast_dir / "tokenizer.json").read_text() + " ")
    with pytest.raises(xt.XingTokenizerError):
        xt.load_tokenizer(fast_dir)
