#!/usr/bin/env python3
"""Native synthetic qualifier for the approximate tensor-API attention research candidate.

Scope: synthetic primitive approximate DENSE attention only (B1, materialized
float16 KV) for ``mlx2.adapters.tensor_fa_research``. Not recurrent state,
prefix cache, model, ragged batch, MTP acceptance, serving or end-to-end
gain. A pass here is a native synthetic gate, never qualification or
selection; ``qualified``/``selected``/``model_gain`` are always false.

Evidence vs execution: ``evaluate()`` judges supplied evidence (dicts, JSON)
and can NEVER establish native execution, whatever the evidence says. Only
the live in-process run object built by ``_run_native`` (after source/build
admission, with the real ``NativeBackend`` and its counters) can stamp
``native_synthetic_gate``; a JSON round trip drops it. This is a trust
boundary against forged reports and fake backends, not a security claim
against arbitrary code that monkeypatches this module.

Identity association: the native backend class, the live-run type, the
witness and the evaluator are captured ONCE, at import, in the closure that
defines ``_run_native`` and ``native_verdict`` (not in default arguments a
caller could override). Rebinding the module names ``NativeBackend``,
``_LiveNativeRun``, ``_WITNESS`` or ``evaluate`` afterwards, a subclass or a
look-alike cannot make a CPU fake count as native, and ``_run_native`` still
constructs the original class. Evidence-association hygiene only: it does
not resist code that edits closures, class attributes or private objects.

Timing is NOT implemented: ``--timing`` is refused before any admission or
backend work. Controlled fair kernel/conversion timing is a pending stage.

Two references, never mixed:
  * host: independent float64 stable softmax over exactly the visible keys,
    regenerated by the evaluator from the catalogue seed. It validates the
    inputs, masks, witnesses and stub evidence; it is not native fidelity.
  * native: ``mx.fast.scaled_dot_product_attention`` on the same visible keys
    with native GQA (un-tiled KV heads) in float16. SDPA needs one dtype for
    q/k/v, so for float32-query cells this baseline rounds q DOWN to float16
    (the two arms do not share query precision); the host float64 reference
    uses the actual q, and a float32 native SDPA run is a diagnostic only.
    The candidate's ``reference_attention`` (repeats KV to Hq, casts fp32) is
    never used.

Nothing imports MLX at module import, ``--help``, ``--catalogue`` or
admission. ``--run-native`` requires ``--i-own-the-gpu`` (an acknowledgement,
NOT ownership: the parent wrapper /tmp/mlx2-intake/stage3_gpu.py owns the CPG
lease and both flocks), ``--source-root`` equal to this checkout, and
``--source-commit`` equal to MLX2_INTAKE_SOURCE_COMMIT and git HEAD. Before
any MLX import: a clean tracked+untracked status for src/scripts/tests/
provenance, every bound file's hash equal to its blob at HEAD, and the
installed MLX core extension, libmlx and metallib hashed. After importing MLX
and before any device query, the imported extension (``mx.__file__``) and
``mx.__version__`` must match that snapshot. Before EVERY backend dispatch
the bound source and MLX files must still equal the admitted snapshot (the
run stops otherwise), and after the run HEAD, clean status, hashes, build
and module paths are re-checked. No CPU fallback. A receipt is written only
with ``--out`` (exclusive creation) after a completed run.

  # run from this checkout; the isolated worktree has no .venv, and the parent wrapper's
  # source-root and CPG workflow/task defaults are obsolete, so all four are explicit:
  MLX2_INTAKE_SOURCE_ROOT=<this checkout> MLX2_INTAKE_SOURCE_COMMIT=<full HEAD sha> \\
  MLX2_INTAKE_CPG_WORKFLOW=<fresh live workflow> MLX2_INTAKE_CPG_TASK=<fresh native task> \\
  python /tmp/mlx2-intake/stage3_gpu.py tensor-fa-native \\
      ~/Desktop/mlx2/.venv/bin/python scripts/qualify_tensor_fa_research.py \\
      --run-native --i-own-the-gpu --source-root <this checkout> --source-commit <full HEAD sha> \\
      --out <new receipt>.json
"""

from __future__ import annotations

import argparse
import hashlib
import importlib.metadata
import importlib.util
import json
import math
import os
import re
import subprocess
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(ROOT))

SCHEMA = "mlx2.native.tensor-fa-synthetic-gate.v1"
SCOPE = ("synthetic primitive approximate dense attention only (B1, materialized float16 KV); not recurrent state, "
         "prefix cache, model, ragged batch, MTP acceptance, serving or end-to-end gain")
SOURCE_FILES = (
    "src/mlx2/adapters/tensor_fa_research.py",
    "tests/test_tensor_fa_research.py",
    "provenance/tensor-fa-research.json",
    "provenance/tensor-fa-research.NOTICE",
    "scripts/qualify_tensor_fa_research.py",
    "tests/test_tensor_fa_research_qualifier.py",
    "tests/test_tensor_fa_native_identity_cpu.py",
    "provenance/tensor-fa-native-qualifier.json",
)
STATUS_PATHS = ("src", "scripts", "tests", "provenance")
CANDIDATE_MODULE = "src/mlx2/adapters/tensor_fa_research.py"
Q_ROWS, C_KEYS, HALF_MAX = 32, 64, 65504.0
BASELINE = {"kind": "mx.fast.scaled_dot_product_attention", "kv": "native GQA (un-tiled KV heads)", "dtype": "float16"}
# Predeclared; never adapted to observed outputs (approximate math is not bit-exact).
TOLERANCE = {
    "native_f16": {"normalized_max": 0.015, "normalized_rms": 0.003, "min_row_cosine": 0.9995},
    "host_f64": {"normalized_max": 0.01, "normalized_rms": 0.002, "min_row_cosine": 0.9995},
}
VERDICT_KEYS = {"qualified", "selected", "native_synthetic_gate", "verdict", "model_gain", "native"}
SHA = re.compile(r"[0-9a-f]{64}")


class Refused(RuntimeError):
    """Fail closed: never a pass."""


# ================================================================ catalogue (pure)

def _case(cid, dim, q_dtype, hq, hkv, length, kv_len, causal, q_start, law, expect="pass", optional=False):
    blocks = -(-length // Q_ROWS)
    kv_end = [min(kv_len, -(-(q_start + min((b + 1) * Q_ROWS, length)) // C_KEYS) * C_KEYS) if causal else kv_len
              for b in range(blocks)]
    qb = 4 if q_dtype == "float32" else 2
    memory = {  # bytes held at once in one native cell (inputs, f32 diagnostic copies, three outputs)
        "inputs": hq * length * dim * qb + 2 * hkv * kv_len * dim * 2,
        "f32_diagnostic_inputs": (hq * length + 2 * hkv * kv_len) * dim * 4,
        "outputs": hq * length * dim * (4 + 2 + 4),
    }
    memory["total"] = sum(memory.values())
    return {"id": cid, "dim": dim, "q_dtype": q_dtype, "hq": hq, "hkv": hkv, "length": length, "kv_len": kv_len,
            "causal": causal, "q_start": q_start, "law": law, "expect": expect, "optional": optional,
            "scale": 1.0 / math.sqrt(dim), "expected_threadgroups": blocks * hq, "kv_end": kv_end,
            "expected_memory_bytes": memory}


CATALOGUE = (
    _case("c01-d128-f16-g1-w1-start0", 128, "float16", 1, 1, 1, 64, True, 0, "random"),
    _case("c02-d128-f32-g2-w17-final", 128, "float32", 2, 1, 17, 128, True, 111, "random"),
    _case("c03-d128-f16-g6-w31-mid", 128, "float16", 12, 2, 31, 256, True, 100, "random"),
    _case("c04-d256-f16-g2-w32-final", 256, "float16", 4, 2, 32, 256, True, 224, "random"),
    _case("c05-d256-f32-g1-w33-start0", 256, "float32", 2, 2, 33, 512, True, 0, "random"),
    _case("c06-d128-f16-g6-w65-dense", 128, "float16", 12, 2, 65, 1024, False, 0, "random"),
    _case("c07-d256-f16-g6-w65-final", 256, "float16", 12, 2, 65, 512, True, 447, "random"),
    _case("c08-d128-f32-g2-w33-large-logits", 128, "float32", 4, 2, 33, 256, True, 223, "large_logits"),
    _case("c09-d128-f16-g2-w32-rescale-mixed", 128, "float16", 2, 1, 32, 256, False, 0, "rescale_mixed"),
    _case("c10-d256-f32-g1-w17-rescale-mixed", 256, "float32", 2, 2, 17, 256, False, 0, "rescale_mixed"),
    _case("r01-d128-f32-half-scaled-overflow", 128, "float32", 2, 1, 4, 64, True, 60, "half_overflow", expect="refuse"),
    _case("r02-d128-f16-nonfinite-v", 128, "float16", 2, 1, 4, 64, True, 60, "nonfinite_v", expect="refuse"),
    _case("t01-d256-f16-g6-w32-n8192-timing", 256, "float16", 12, 2, 32, 8192, True, 8160, "random", optional=True),
)
MANDATORY = tuple(c["id"] for c in CATALOGUE if not c["optional"])
TIMING_CELLS = tuple(c["id"] for c in CATALOGUE if c["optional"])


def catalogue_by_id():
    ids = [c["id"] for c in CATALOGUE]
    if len(set(ids)) != len(ids):
        raise Refused("duplicate catalogue identity")
    return {c["id"]: c for c in CATALOGUE}


def select_cases(ids=None):
    """Default: the mandatory catalogue (full). Explicit ids, including the catalogue-only optional
    cell (numeric evidence only), are a partial run."""
    table = catalogue_by_id()
    if ids is None:
        chosen = list(MANDATORY)
    else:
        chosen = list(ids)
        unknown = [i for i in chosen if i not in table]
        if unknown or len(set(chosen)) != len(chosen):
            raise Refused(f"unknown or duplicate case ids {unknown or chosen}")
    return [table[i] for i in chosen], ids is None


# ================================================================ inputs and host law (pure numpy)

def _rng(case):
    import numpy as np

    return np.random.default_rng(int.from_bytes(hashlib.sha256(case["id"].encode()).digest()[:8], "little"))


def host_inputs(case):
    """Deterministic logical inputs as numpy arrays in the dtypes the candidate receives."""
    import numpy as np

    rng, d = _rng(case), case["dim"]
    q = rng.standard_normal((1, case["hq"], case["length"], d))
    k = rng.standard_normal((1, case["hkv"], case["kv_len"], d))
    v = rng.standard_normal((1, case["hkv"], case["kv_len"], d))
    if case["law"] == "large_logits":
        q *= 40.0                                       # scores of order +-40..120; q*scale stays well below half max
    elif case["law"] == "rescale_mixed":
        q *= 0.5
        k *= 0.5
        u = rng.standard_normal(d)
        u /= np.linalg.norm(u)
        q[:, :, 0::2, :] += (20.0 / (case["scale"] * 4.0)) * u   # even rows: later-block scores jump by ~20
        k[:, :, 128:192, :] += 4.0 * u                           # key block 2 only
    elif case["law"] == "half_overflow":
        q[0, 0, 0, 0] = 1.0e7                           # q*scale far above half max
    elif case["law"] == "nonfinite_v":
        v[0, 0, 3, 5] = np.nan
    qd = np.float16 if case["q_dtype"] == "float16" else np.float32
    return {"q": q.astype(qd), "k": k.astype(np.float16), "v": v.astype(np.float16)}


def input_hashes(inputs):
    return {name: hashlib.sha256(arr.tobytes()).hexdigest() for name, arr in inputs.items()}


def visible_mask(case):
    import numpy as np

    rows = case["q_start"] + np.arange(case["length"])[:, None]
    keys = np.arange(case["kv_len"])[None, :]
    return keys <= rows if case["causal"] else np.ones((case["length"], case["kv_len"]), dtype=bool)


def host_reference(case, inputs):
    """float64 stable softmax over exactly the visible keys (GQA by head grouping)."""
    import numpy as np

    q, k, v = (inputs[n].astype(np.float64) for n in ("q", "k", "v"))
    group = case["hq"] // case["hkv"]
    mask = visible_mask(case)
    out = np.zeros(q.shape, dtype=np.float64)
    for h in range(case["hq"]):
        s = q[0, h] @ k[0, h // group].T * case["scale"]
        s = np.where(mask, s, -np.inf)
        w = np.exp(s - s.max(axis=1, keepdims=True))
        out[0, h] = (w / w.sum(axis=1, keepdims=True)) @ v[0, h // group]
    return out


def precheck(case, inputs):
    """Host refusals before any native call (never counted as a numeric pass)."""
    import numpy as np

    for name, arr in inputs.items():
        if not np.isfinite(arr.astype(np.float64)).all():
            return f"non-finite {name} input"
    scaled = np.abs(inputs["q"].astype(np.float64) * np.float32(case["scale"]))
    if scaled.max() >= HALF_MAX:
        return "half-scaled query overflow (q*scale >= 65504)"
    return None


def rescale_witness(case, inputs):
    """From the inputs alone (float64): rows that must rescale mid-loop and rows that must not.

    A grow row's later-block max exceeds its earlier running max by > 8 (the
    lazy threshold) and by > ln(65504), so DELETING that rescale would overflow
    the half probabilities; a stay row never exceeds by more than 8.
    """
    import numpy as np

    q, k = inputs["q"].astype(np.float64), inputs["k"].astype(np.float64)
    group = case["hq"] // case["hkv"]
    mask = visible_mask(case)
    grow = stay = 0
    for h in range(case["hq"]):
        s = np.where(mask, q[0, h] @ k[0, h // group].T * case["scale"], -np.inf)
        first = s[:, :C_KEYS].max(axis=1)
        later = s[:, C_KEYS:].max(axis=1) if s.shape[1] > C_KEYS else np.full(len(first), -np.inf)
        grow += int(np.sum(later > first + max(8.0, math.log(HALF_MAX))))
        stay += int(np.sum(later <= first + 8.0))
    return {"grow_rows": grow, "stay_rows": stay}


def _metrics(candidate, reference):
    import numpy as np

    c, r = candidate.astype(np.float64), reference.astype(np.float64)
    diff = c - r
    cos = (c * r).sum(-1) / np.maximum(np.linalg.norm(c, axis=-1) * np.linalg.norm(r, axis=-1), 1e-300)
    return {"normalized_max": float(np.abs(diff).max() / max(np.abs(r).max(), 1e-300)),
            "normalized_rms": float(np.sqrt((diff ** 2).mean()) / max(np.sqrt((r ** 2).mean()), 1e-300)),
            "min_row_cosine": float(cos.min())}


def _within(metrics, tol):
    return (metrics["normalized_max"] <= tol["normalized_max"] and metrics["normalized_rms"] <= tol["normalized_rms"]
            and metrics["min_row_cosine"] >= tol["min_row_cosine"])


# ================================================================ evaluation (pure)

def _array_ok(value, dtype, shape):
    import numpy as np

    if not isinstance(value, np.ndarray):
        return "missing array"
    if str(value.dtype) != dtype or tuple(value.shape) != tuple(shape):
        return f"dtype/shape {value.dtype}{tuple(value.shape)} != {dtype}{tuple(shape)}"
    if not np.isfinite(value.astype(np.float64)).all():
        return "non-finite values"
    return None


def evaluate_case(case, ev):
    """Problems (refusals) and per-case metrics for one case's evidence."""
    import numpy as np

    problems = []
    if not isinstance(ev, dict):
        return ["evidence missing"], {}
    if VERDICT_KEYS & set(ev):
        return [f"evidence carries verdict fields {sorted(VERDICT_KEYS & set(ev))}"], {}
    inputs = host_inputs(case)
    if ev.get("input_hashes") != input_hashes(inputs):
        problems.append("input identity hashes differ from the catalogue law")
    before, after = ev.get("source_before"), ev.get("source_after")
    if not isinstance(before, dict) or not before or before != after or any(not SHA.fullmatch(str(x)) for x in before.values()):
        problems.append("source hashes missing or changed during the case")
    if case["expect"] == "refuse":
        reason = precheck(case, inputs)
        if reason is None:
            problems.append("catalogue refuse case is not refused by the host law")
        if ev.get("refused") != reason or any(k in ev for k in ("candidate", "baseline_f16", "engagement")):
            problems.append("refuse case must be refused before any native call, with no outputs")
        return problems, {}
    if ev.get("refused"):
        return [f"refused unexpectedly: {ev['refused']}"], {}
    shape = (1, case["hq"], case["length"], case["dim"])
    for name, dtype in (("candidate", "float32"), ("baseline_f16", "float16")):
        bad = _array_ok(ev.get(name), dtype, shape)
        if bad:
            problems.append(f"{name}: {bad}")
    # Optional float32 SDPA diagnostic: if present it must be a full finite float32 array; it may be absent
    # only when the evidence explicitly declares it omitted. It never replaces the mandatory references.
    if "baseline_f32" in ev:
        bad = _array_ok(ev["baseline_f32"], "float32", shape)
        if bad:
            problems.append(f"baseline_f32 diagnostic: {bad}")
    elif ev.get("baseline_f32_scope") != "omitted":
        problems.append("baseline_f32 diagnostic absent without an explicit 'omitted' scope")
    if ev.get("baseline_meta") != {**BASELINE, "kv_heads": case["hkv"], "q_heads": case["hq"]}:
        problems.append("baseline is not ordinary native-GQA float16 sdpa on the same heads")
    plan = ev.get("plan") or {}
    if plan.get("threadgroups") != case["expected_threadgroups"] or plan.get("kv_end") != case["kv_end"]:
        problems.append("plan threadgroups/kv_end differ from the catalogue law")
    eng = ev.get("engagement") or {}
    want = case["expected_threadgroups"]
    if not (want > 0 and eng.get("confirmed") is True and eng.get("observed_threadgroups") == want
            and eng.get("expected_threadgroups") == want and eng.get("issued_delta") == 1
            and eng.get("confirmed_delta") == 1):
        problems.append("engagement not confirmed with the expected nonzero threadgroup count and counter deltas")
    reference = host_reference(case, inputs)
    if np.abs(reference).max() < 1e-3 or np.ptp(inputs["v"].astype(np.float64)) == 0:
        problems.append("vacuous reference")
    metrics = {}
    if case["law"] == "rescale_mixed":
        metrics["witness"] = rescale_witness(case, inputs)
        if metrics["witness"]["grow_rows"] < 1 or metrics["witness"]["stay_rows"] < 1:
            problems.append("rescale witness needs both growing and non-growing rows")
    if problems:
        return problems, metrics
    metrics["vs_host_f64"] = _metrics(ev["candidate"], reference)
    metrics["vs_native_f16"] = _metrics(ev["candidate"], ev["baseline_f16"])
    if "baseline_f32" in ev:                     # admitted above; diagnostic only, no acceptance threshold
        metrics["vs_native_f32_diagnostic"] = _metrics(ev["candidate"], ev["baseline_f32"])
    if not _within(metrics["vs_host_f64"], TOLERANCE["host_f64"]):
        problems.append(f"candidate outside host float64 tolerance {metrics['vs_host_f64']}")
    if not _within(metrics["vs_native_f16"], TOLERANCE["native_f16"]):
        problems.append(f"candidate outside native float16 sdpa tolerance {metrics['vs_native_f16']}")
    return problems, metrics


def evaluate(report, cases, *, full_requested):
    """Verdict over a report. Every verdict field is computed here, never read from evidence."""
    refusals, per_case = [], {}
    records = report.get("cases")
    if not isinstance(records, list):
        records = []
        refusals.append("no case evidence")
    ids = [r.get("id") if isinstance(r, dict) else None for r in records]
    for i in sorted({i for i in ids if ids.count(i) > 1}, key=str):
        refusals.append(f"duplicate case {i}")
    want = [c["id"] for c in cases]
    refusals += [f"missing case {i}" for i in want if i not in ids]
    refusals += [f"unexpected case {i}" for i in ids if i not in want]
    if full_requested and set(want) != set(MANDATORY) | (set(want) & set(TIMING_CELLS)):
        refusals.append("full gate requested with an incomplete mandatory catalogue")
    table = {c["id"]: c for c in cases}
    for record in records:
        case = table.get(record.get("id")) if isinstance(record, dict) else None
        if case is None:
            continue
        if "timing" in record:
            refusals.append(f"{case['id']}: timing evidence is not accepted (timing is not implemented)")
        problems, metrics = evaluate_case(case, record.get("evidence"))
        per_case[case["id"]] = {"problems": problems, "metrics": metrics}
        refusals += [f"{case['id']}: {p}" for p in problems]
    verdict = ("refused" if refusals else "numeric_evidence_pass" if full_requested else "partial_numeric_evidence")
    # Evidence evaluation never establishes native execution: the fields below are constants here.
    return {"verdict": verdict, "refusals": refusals, "per_case": per_case, "full_requested": full_requested,
            "native_synthetic_gate": False, "qualified": False, "selected": False, "model_gain": False,
            "scope": SCOPE, "evidence_label": "evaluation of supplied evidence; does not establish native execution"}


# ================================================================ admission (no MLX)

def _git(*args):
    try:
        return subprocess.run(["git", *args], cwd=ROOT, capture_output=True, check=True).stdout
    except (OSError, subprocess.CalledProcessError):
        return None


def source_hashes():
    return {p: hashlib.sha256((ROOT / p).read_bytes()).hexdigest() for p in SOURCE_FILES if (ROOT / p).exists()}


def mlx_files():
    """Hash the installed MLX core extension, libmlx and metallib WITHOUT importing MLX."""
    spec = importlib.util.find_spec("mlx")
    if spec is None or not spec.submodule_search_locations:
        raise Refused("MLX is not installed")
    base = Path(list(spec.submodule_search_locations)[0])
    files = sorted(base.glob("core*.so")) + [base / "lib" / "libmlx.dylib", base / "lib" / "mlx.metallib"]
    if len(files) != 3 or not all(f.exists() for f in files):
        raise Refused("MLX core extension, libmlx or metallib missing")
    return {str(f): hashlib.sha256(f.read_bytes()).hexdigest() for f in files}


def same_snapshot(observed, expected):
    """Exact equality of two {path: sha256} snapshots (no missing, extra or malformed entries)."""
    return (isinstance(observed, dict) and isinstance(expected, dict) and bool(expected)
            and set(observed) == set(expected) and all(SHA.fullmatch(str(v)) for v in expected.values())
            and all(observed[k] == expected[k] for k in expected))


def import_identity_refusal(admission, mx_file, mx_version):
    """After ``import mlx.core`` and BEFORE any device query: the imported extension must be the admitted one."""
    files = admission.get("mlx_files_before") or {}
    core = str(Path(mx_file).resolve())
    if core not in files:
        return "imported mlx.core extension is not the admitted file"
    if hashlib.sha256(Path(core).read_bytes()).hexdigest() != files[core]:
        return "imported mlx.core extension bytes differ from admission"
    if mx_version != admission.get("mlx_version"):
        return "imported MLX version differs from the admitted package metadata"
    return None


def source_guard(admission):
    """Before each dispatch and after each case: the admitted HEAD, a clean tracked+untracked
    src/scripts/tests/provenance, and bound source and MLX files equal to the admission."""
    if (_git("rev-parse", "HEAD") or b"").decode().strip() != admission["commit"]:
        raise Refused("git HEAD differs from the admitted commit")
    status = _git("status", "--porcelain", "--untracked-files=all", "--", *STATUS_PATHS)
    if status is None or status.strip():
        raise Refused("source tree (src/scripts/tests/provenance) is not clean or status unavailable")
    if not same_snapshot(source_hashes(), admission["source_expected"]):
        raise Refused("bound source files changed since admission")
    if not same_snapshot(mlx_files(), admission["mlx_files_before"]):
        raise Refused("installed MLX files changed since admission")


def post_run_refusals(admission, candidate_file, mx_file):
    refusals = []
    try:
        source_guard(admission)
    except Refused as error:
        refusals.append(str(error))
    if Path(candidate_file).resolve() != ROOT / CANDIDATE_MODULE:
        refusals.append("candidate module path is not this checkout's")
    if str(Path(mx_file).resolve()) not in admission["mlx_files_before"]:
        refusals.append("mlx.core path is not the admitted extension")
    return refusals


def native_admission(args, environ):
    """Everything that must hold before any MLX import or device query."""
    if not args.run_native:
        raise Refused("no --run-native: this qualifier has no CPU fallback")
    if args.i_own_the_gpu is not True:
        raise Refused("--i-own-the-gpu acknowledgement missing (ownership itself is the parent wrapper's receipt)")
    if not args.source_root or Path(args.source_root).resolve() != ROOT:
        raise Refused(f"--source-root must be this checkout ({ROOT})")
    commit = environ.get("MLX2_INTAKE_SOURCE_COMMIT", "")
    if not re.fullmatch(r"[0-9a-f]{40}", str(args.source_commit or "")) or args.source_commit != commit:
        raise Refused("--source-commit must be a full sha equal to MLX2_INTAKE_SOURCE_COMMIT")
    head = (_git("rev-parse", "HEAD") or b"").decode().strip()
    if head != args.source_commit:
        raise Refused("git HEAD does not equal the source commit")
    status = _git("status", "--porcelain", "--untracked-files=all", "--", *STATUS_PATHS)
    if status is None or status.strip():
        raise Refused("source tree (src/scripts/tests/provenance) is not clean or status unavailable")
    observed = source_hashes()
    expected = {}
    for path in SOURCE_FILES:
        blob = _git("show", f"HEAD:{path}")
        if blob is None:
            raise Refused(f"{path} is not committed at HEAD")
        expected[path] = hashlib.sha256(blob).hexdigest()
    if observed != expected:
        raise Refused("working source differs from HEAD blobs")
    if args.out is None:
        raise Refused("--out is required for a native run")
    if Path(args.out).exists():
        raise Refused("--out exists; refusing to overwrite a receipt")
    return {"commit": head, "source_expected": expected, "mlx_files_before": mlx_files(),
            "mlx_version": importlib.metadata.version("mlx")}


# ================================================================ orchestration

def run_gate(backend, cases, *, source=source_hashes, guard=None):
    """One case at a time. ``guard`` runs before every dispatch and after every case (raises to stop).

    The returned report is EVIDENCE: it carries no execution status.
    """
    records = []
    for case in cases:
        try:
            if guard is not None:
                guard()
            before = source()
            inputs = host_inputs(case)
            evidence = {"input_hashes": input_hashes(inputs)}
            reason = precheck(case, inputs)
            if reason is not None:
                evidence["refused"] = reason
            else:
                evidence.update(backend.run_case(case, inputs))
            evidence["source_before"], evidence["source_after"] = before, source()
            records.append({"id": case["id"], "evidence": evidence})
        finally:
            backend.release()
        if guard is not None:
            guard()
    return {"producer": type(backend).__name__, "cases": records, "identity": backend.identity()}


class NativeBackend:
    """Real Metal backend; constructed only after native_admission (never in CPU tests)."""

    def __init__(self, admission):
        import mlx.core as mx

        refusal = import_identity_refusal(admission, mx.__file__, mx.__version__)
        if refusal:                                      # before ANY device query
            raise Refused(refusal)
        if mx.default_device() != mx.gpu or not mx.metal.is_available():
            raise Refused("default device is not an available GPU")
        info = dict(mx.device_info())
        if not str(info.get("architecture", "")).startswith("applegpu_g17"):
            raise Refused("not an M5-class (tensor API) device")
        from mlx2.adapters import tensor_fa_research as cand

        if Path(cand.__file__).resolve() != ROOT / CANDIDATE_MODULE:
            raise Refused("candidate module was not imported from this checkout")
        if not same_snapshot(mlx_files(), admission["mlx_files_before"]):
            raise Refused("installed MLX changed between admission and import")
        self.mx, self.cand, self.admission, self.info = mx, cand, admission, info

    def identity(self):
        return {"default_device": "gpu" if self.mx.default_device() == self.mx.gpu else "other",
                "architecture": str(self.info.get("architecture")),
                "device_info": {k: str(v) for k, v in self.info.items()},
                "mlx_version": self.mx.__version__, "mlx_files_before": self.admission["mlx_files_before"],
                "mlx_files_after": mlx_files(), "candidate_module": str(Path(self.cand.__file__).resolve()),
                "commit": self.admission["commit"]}

    def _arrays(self, case, inputs):
        mx = self.mx
        arrays = {n: mx.array(a) for n, a in inputs.items()}
        mx.eval(list(arrays.values()))
        return arrays

    def _mask(self, case):
        import numpy as np

        return self.mx.array(visible_mask(case)) if case["causal"] else None

    def _baseline(self, case, q, k, v, dtype):
        mx = self.mx
        return mx.fast.scaled_dot_product_attention(q.astype(dtype), k.astype(dtype), v.astype(dtype),
                                                    scale=case["scale"], mask=self._mask(case))

    def run_case(self, case, inputs):
        import numpy as np

        mx, cand = self.mx, self.cand
        a = self._arrays(case, inputs)
        before = cand.status()
        out, engaged, plan = cand.tensor_fa_attention(a["q"], a["k"], a["v"], scale=case["scale"],
                                                      causal=case["causal"], q_start=case["q_start"],
                                                      allow_research_metal=True)
        mx.eval(out, engaged)
        observed = int(engaged.item())
        confirmed = cand.confirm_engagement(engaged)
        after = cand.status()
        candidate = np.array(out)
        del out
        base16 = self._baseline(case, a["q"], a["k"], a["v"], mx.float16)
        mx.eval(base16)
        b16 = np.array(base16)
        del base16
        base32 = self._baseline(case, a["q"], a["k"], a["v"], mx.float32)
        mx.eval(base32)
        b32 = np.array(base32)
        del base32, a
        return {"candidate": candidate, "baseline_f16": b16, "baseline_f32": b32,
                "baseline_meta": {**BASELINE, "kv_heads": case["hkv"], "q_heads": case["hq"]},
                "plan": {"threadgroups": plan.threadgroups, "kv_end": list(plan.kv_end)},
                "engagement": {"expected_threadgroups": plan.threadgroups, "observed_threadgroups": observed,
                               "confirmed": confirmed,
                               "issued_delta": after["native_launches_issued"] - before["native_launches_issued"],
                               "confirmed_delta": (after["native_engagement_confirmed"]
                                                   - before["native_engagement_confirmed"])}}

    def release(self):
        self.mx.synchronize()
        self.mx.clear_cache()


_WITNESS = object()   # module-private; held only by live runs built in _run_native


class _LiveNativeRun:
    """In-process record of an actual native orchestration (never serialized)."""

    __slots__ = ("_witness", "backend", "admission", "report", "post_run", "cases", "full_requested")

    def __init__(self, witness, backend, admission, report, post_run, cases, full_requested):
        self._witness, self.backend, self.admission = witness, backend, admission
        self.report, self.post_run = report, list(post_run)
        self.cases, self.full_requested = tuple(cases), bool(full_requested)


def _bind_native_identity(native_cls, live_cls, witness, evaluator):
    """Capture the original native class, live-run type, witness and evaluator at import.

    Closure cells, not default arguments: no caller argument can substitute a class or evaluator, and
    rebinding the module names later changes neither what ``_run_native`` constructs nor what
    ``native_verdict`` accepts.
    """

    def _run_native(admission, cases, full_requested):
        backend = native_cls(admission)
        report = run_gate(backend, cases, guard=lambda: source_guard(admission))
        post = post_run_refusals(admission, backend.cand.__file__, backend.mx.__file__)
        return live_cls(witness, backend, admission, report, post, cases, full_requested)

    def native_verdict(live):
        """The ONLY place a native synthetic gate can be stamped: a live run object, never a dict/JSON.

        The numeric evaluation is computed HERE from this run's own report, catalogue cases and scope;
        no caller-supplied evaluation can be associated with a run.
        """
        reasons = []
        report = getattr(live, "report", None)
        cases = getattr(live, "cases", None)
        full = getattr(live, "full_requested", False) is True
        if isinstance(report, dict) and isinstance(cases, (list, tuple)) and cases:
            evaluation = evaluator(report, list(cases), full_requested=full)
        else:
            evaluation = {"verdict": "refused", "refusals": ["no live report/cases"], "native_synthetic_gate": False}
        if type(live) is not live_cls or getattr(live, "_witness", None) is not witness:
            reasons.append("no live native orchestration (evidence alone never establishes native execution)")
        elif type(live.backend) is not native_cls:
            reasons.append("backend is not the native backend")
        else:
            reasons += live.post_run
        if evaluation.get("verdict") != "numeric_evidence_pass":
            reasons.append("numeric evidence did not pass the full mandatory catalogue")
        return {"native_synthetic_gate": not reasons, "reasons": reasons, "evaluation": evaluation,
                "qualified": False, "selected": False, "model_gain": False}

    _run_native.__qualname__, native_verdict.__qualname__ = "_run_native", "native_verdict"
    return _run_native, native_verdict


_run_native, native_verdict = _bind_native_identity(NativeBackend, _LiveNativeRun, _WITNESS, evaluate)


# ================================================================ CLI

def build_parser():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--catalogue", action="store_true", help="print the catalogue (no MLX import)")
    ap.add_argument("--run-native", action="store_true")
    ap.add_argument("--i-own-the-gpu", action="store_true")
    ap.add_argument("--source-root")
    ap.add_argument("--source-commit")
    ap.add_argument("--cases", nargs="+", help="partial run (labelled partial, never a full gate)")
    ap.add_argument("--timing", action="store_true", help="refused: controlled fair timing is not implemented")
    ap.add_argument("--out")
    return ap


def _jsonable(report):
    import numpy as np

    def clean(x):
        if isinstance(x, np.ndarray):
            return {"dtype": str(x.dtype), "shape": list(x.shape), "sha256": hashlib.sha256(x.tobytes()).hexdigest()}
        if isinstance(x, dict):
            return {k: clean(v) for k, v in x.items()}
        if isinstance(x, list):
            return [clean(v) for v in x]
        return x

    return clean(report)


def main(argv=None, environ=None):
    args = build_parser().parse_args(argv)
    environ = os.environ if environ is None else environ
    if args.catalogue:
        print(json.dumps({"mandatory": MANDATORY, "catalogue_only_optional": TIMING_CELLS, "cases": CATALOGUE},
                         indent=1))
        return 0
    try:
        if args.timing:                                              # before any admission/backend/device work
            raise Refused("timing is not implemented: controlled fair kernel/conversion timing is a pending stage")
        cases, full = select_cases(args.cases)
        admission = native_admission(args, environ)                 # before any MLX import
        live = _run_native(admission, cases, full)
        native = native_verdict(live)                               # evaluation bound to this live run
        evaluation = native.pop("evaluation")
    except Refused as error:
        print(json.dumps({"verdict": "refused", "refusals": [str(error)], "native_synthetic_gate": False,
                          "qualified": False, "selected": False, "model_gain": False}))
        return 1
    receipt = {"schema": SCHEMA, "scope": SCOPE, "tolerance": TOLERANCE, "evaluation": evaluation,
               "native_execution": native, "report": _jsonable(live.report),
               "qualified": False, "selected": False, "model_gain": False,
               "note": "native_execution was stamped in-process; re-evaluating this JSON can never re-establish it"}
    with open(args.out, "x") as handle:                              # exclusive creation, completed runs only
        json.dump(receipt, handle, indent=1)
    print(json.dumps({"verdict": evaluation["verdict"], **native}))
    return 0 if native["native_synthetic_gate"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
